export default {
    accents: {
        beige: '#FFEDCF',
        red: '#FF404A',
        yellow: '#FFD626',
    },
    backgrounds: {
        blue: '#e6f0fb',
        blueLight: '#f4fcff',
        green: '#ebfbf3',
        greenLight: '#ecfafa',
        pink: '#ffe2f2',
        pinkLight: '#fff6fb',
        gray: '#FAF8F5',
    },
    black: '#000000',
    grey: '#979797',
    greyLight: '#DBEDF5',
    red: '#FF0000',
    error: '#E0AD8B',
    sequence: ['#4D45BF', '#FF4FB5', '#30C4FF', '#32AA6F'],
    theme: {
        blue: '#4D45BF',
        blueLight: '#30C4FF',
        cream: '#F5F2ED',
        green: '#78C4BE',
        peach: '#F9885E',
        pink: '#ff50b5',
        pinkLight: '#FFD7D2',
        purple: '#6978F6',
        purpleLight: '#B1B9FA',
    },
    themeExtended: {
        creamDark: '#DBD8D3',
    },
    transparent: 'rgba(0, 0, 0, 0.0)',
    white: '#FFFFFF',
};
